version: "3"

services:
  rstudio:
    build: 
      context: ./docker/
      dockerfile: Dockerfile
    container_name: myrocker-shiny
    image: nujabec/myrocker-shiny:20240411
    ports:
      - "8787:8787"
      - "3838:3838"
    volumes:
      - ../srv/:/home/rstudio/srv/
      - ../srv/shinyapps:/srv/shiny-server/
      - ../srv/shinylog:/var/log/shiny-server/
      - renv:/home/rstudio/.cache/R/renv
    environment:
      PASSWORD: rs
      ROOT: "TRUE"
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true
    restart: always
volumes:
  renv:
    external: true
