version: "3"

services:
  rstudio:
    build: 
      context: ./docker/
      dockerfile: Dockerfile
    image: nujabec/myrocker-shiny:20241018
    ports:
      - "8781:8787"
      - "81:3838"
    volumes:
      - ../srv/:/home/rstudio/srv/
      - ../srv/shinyapps:/srv/shiny-server/
      - ../srv/shinylog:/var/log/shiny-server/
      - renv:/home/rstudio/.cache/R/renv
    environment:
      PASSWORD: rs
      ROOT: "TRUE"
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true
    restart: always
    networks:
      - pgnetwork

volumes:
  renv:
    external: true

networks:
    pgnetwork:
      external: true